CREATE TABLE game_history_2048 (
	ID INT(16) PRIMARY KEY AUTO_INCREMENT,
	DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MOVES INT(10) NOT NULL,
	SCORE INT(10) NOT NULL,
	MAXRANK INT(5) NOT NULL,
	BOARD VARCHAR(16) NOT NULL
);

